name: Build & Push Docker image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:   # 手动触发按钮

env:
  IMAGE_NAME: 0xcccccccccccc/authelia                         

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}      # 当前仓库所属用户/组织
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (自动生成 tag)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./Dockerfile.dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
